export 'package:crud_flutter/screen/register_user_screen.dart';
export 'package:crud_flutter/screen/loading_screen.dart';
export 'package:crud_flutter/screen/error_screen.dart';
export 'package:crud_flutter/screen/menu.dart';
export 'package:crud_flutter/screen/login_screen.dart';
export 'package:crud_flutter/screen/proveedores/proveedor_edit_screen.dart';
export 'package:crud_flutter/screen/proveedores/proveedores_screen.dart';
export 'package:crud_flutter/screen/categorias/categorias_screen.dart';
export 'package:crud_flutter/screen/productos/productos_screen.dart';
